#!/bin/python3

import os
import sys

def timeConversion(s):
    tim=s[8:]
    x=int(s[0:2])
    if(tim=='PM'):
        if(x<12):
            x+=12
        if(x==12):
            x=12
        if(x>=24):
            x='00'
        res=str(x)+s[2:8]
    else:
        if(x==12):
            x='00'
            res=str(x)+s[2:8]
        else:
            res=s[:8]
    return res

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
